import Head from 'next/head'
import Image from 'next/image'



export default function Home() {

  var myArray = ["a", "b", "v", "f"];
  // jkgjhjk

  return (
    <>
      <Head>
        <title>FEH-UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <center>
        <h1>FEH-UI</h1>
        <h2>These are the units for this round</h2>
        <div> 
    {myArray.map(item => ( 
      <div> 
        <h2>{item}</h2> 
      </div> 
    ))} 
  </div>
  <div>
    {myArray[2]}
  </div>
  </center>
      </main>
    </>
  )
}
